apiVersion: v1
kind: ReplicationController
metadata:
  name: api
spec:
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: 661058921700.dkr.ecr.us-east-1.amazonaws.com/vegeta-api:latest
        command:
        - /api
        - --serve
        - --port=8080
        - --selector=run=vegeta
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
      dnsPolicy: ClusterFirst
