apiVersion: v1
kind: ReplicationController
metadata:
  name: vegeta
spec:
  template:
    metadata:
      labels:
        run: vegeta
    spec:
      containers:
      - name: vegeta
        image: gcr.io/google_containers/loader:0.3
        resources:
          requests:
            cpu: 100m
        command:
          - /loader
          - --serve
          - --port=:8080
          - --rate=1
          - --duration=10s
          # TODO - one worker?
          - --workers=1
      dnsPolicy: ClusterFirst