apiVersion: v1
kind: ReplicationController
metadata:
  name: vegeta
spec:
  template:
    metadata:
      labels:
        run: vegeta
    spec:
      containers:
      - name: vegeta
        image: gcr.io/google_containers/loader:0.3
        resources:
          requests:
            cpu: 100m
        command:
          - /loader
          - -host=yahoo.com
          #- -host=nginx
          #- -rate=1000
          - -rate=1
          - -address=:8080
          #- -workers=10
          - -workers=1
          - -duration=10s
      dnsPolicy: ClusterFirst