# FROM golang:1.9.1

# WORKDIR /go/src/github.com/noahhai/kube-vegeta/grpc/api
# COPY api .
# COPY pb ../pb

# RUN go get -d -v ./...
# RUN go install -v ./...

# EXPOSE 3000

FROM scratch
COPY api/main main

EXPOSE 3000

CMD [ "/main" ]