default:
  auth:
    password: admin@1
    type: password
    username: admin
  cache:
    age: 60
    strategy: cache.server
  domain: qabambe.com
  http: https
  store:
    type: file
  tenant: thoughtsphere
